package com.eulerity.taskmanager.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.LocalDate;

/**
 * JPA entity representing a single task in the task manager.
 *
 * @Entity tells Hibernate that this class maps to a database table.
 * @Table(name = "tasks") names the table explicitly — without this,
 * Hibernate would use the class name ("Task") which is fine, but being
 * explicit avoids surprises if the class is ever renamed.
 *
 * Hibernate reads this class at startup and auto-generates the CREATE TABLE
 * SQL for H2 based on the field types and annotations defined here.
 */
@Entity
@Table(name = "tasks")
public class Task {

    /**
     * Primary key — auto-generated by the database.
     *
     * GenerationType.IDENTITY delegates ID generation to the database's
     * auto-increment feature (H2 supports this). Each new row gets the
     * next available integer ID automatically on INSERT.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The task title — required, may not be null or empty.
     *
     * nullable = false enforces this constraint at the database level,
     * producing a NOT NULL column in the generated SQL. Bean Validation
     * (@NotBlank on the DTO) catches this earlier at the HTTP layer,
     * but the database constraint acts as a final safety net.
     */
    @Column(nullable = false)
    private String title;

    /**
     * An optional longer description of the task.
     * No constraints — may be null or empty.
     */
    private String description;

    /**
     * The date by which the task should be completed.
     *
     * LocalDate stores only a calendar date (year, month, day) with no
     * time zone component, which is appropriate for a due date. Hibernate
     * maps this to a DATE column in H2.
     */
    private LocalDate dueDate;

    /**
     * The priority level of the task: LOW, MEDIUM, or HIGH.
     *
     * @Enumerated(EnumType.STRING) tells Hibernate to store the enum's
     * name (e.g., "HIGH") rather than its ordinal position (e.g., 2).
     * String storage is preferred because ordinal values break if enum
     * constants are ever reordered.
     */
    @Enumerated(EnumType.STRING)
    private Priority priority;

    /**
     * The current status of the task: TODO, IN_PROGRESS, or DONE.
     * Stored as a string for the same reason as priority above.
     */
    @Enumerated(EnumType.STRING)
    private Status status;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * No-argument constructor required by JPA.
     * Hibernate uses reflection to instantiate entities when loading rows
     * from the database — it needs a no-arg constructor to do so.
     */
    public Task() {}

    // -------------------------------------------------------------------------
    // Getters and Setters
    // JPA entities need getters/setters so Hibernate (and Jackson, for JSON
    // serialization) can read and write field values via reflection.
    // -------------------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public Priority getPriority() {
        return priority;
    }

    public void setPriority(Priority priority) {
        this.priority = priority;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }
}
